// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXfgrIug35xeGzGBMUJSmNbK-3hbhUmzI',
    appId: '1:1074756112485:web:1d0fdc9a78d9ab5433368c',
    messagingSenderId: '1074756112485',
    projectId: 'inventory-manager-2a85b',
    authDomain: 'inventory-manager-2a85b.firebaseapp.com',
    storageBucket: 'inventory-manager-2a85b.firebasestorage.app',
    measurementId: 'G-F54VBC8WLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgRMsGY5TfRK3GyvPZF_f8RujYfhD7CJA',
    appId: '1:1074756112485:android:1ba7bbfe404404c833368c',
    messagingSenderId: '1074756112485',
    projectId: 'inventory-manager-2a85b',
    storageBucket: 'inventory-manager-2a85b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAUUzPK8jmb9K2_s2_f6W3PAmIXR3mJAw',
    appId: '1:1074756112485:ios:93f1c4e4898def0b33368c',
    messagingSenderId: '1074756112485',
    projectId: 'inventory-manager-2a85b',
    storageBucket: 'inventory-manager-2a85b.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAUUzPK8jmb9K2_s2_f6W3PAmIXR3mJAw',
    appId: '1:1074756112485:ios:93f1c4e4898def0b33368c',
    messagingSenderId: '1074756112485',
    projectId: 'inventory-manager-2a85b',
    storageBucket: 'inventory-manager-2a85b.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXfgrIug35xeGzGBMUJSmNbK-3hbhUmzI',
    appId: '1:1074756112485:web:a098c03a7199b7ff33368c',
    messagingSenderId: '1074756112485',
    projectId: 'inventory-manager-2a85b',
    authDomain: 'inventory-manager-2a85b.firebaseapp.com',
    storageBucket: 'inventory-manager-2a85b.firebasestorage.app',
    measurementId: 'G-E3JY780CCN',
  );

}